import { PageHeader } from "@/components/ui/PageHeader"
import { EmptyState } from "@/components/ui/EmptyState"

export const metadata = { title: "Rewards · Admin" }

export default function AdminRewardsPage() {
  return (
    <div className="space-y-6">
      <PageHeader
        title="Reward events"
        description="Audit reward events and apply manual adjustments. Phase 3."
      />
      <EmptyState
        title="No reward events to review"
        description="Beyond the signup bonus that's auto-issued today, reward events are generated by Phase 3 tournament workflows."
      />
    </div>
  )
}
